---
- hosts: localhost
  become: yes
  tasks:
  - name: fail for other platforms
    fail:
     msg: "this playbook works only for ubuntu-16.04"
    when:
    - ansible_os_family != "Debian"
  - name: install tree
    apt:
     name: tree
     update_cache: yes
     state: present
